// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"payloadrest/src/bizlogic"
	"payloadrest/src/client"
	"payloadrest/src/controller"
	"payloadrest/src/dao"
)

// Injectors from wire.go:

/**
* using wire dependency injections to initialize the server
**/
func InitializeServer() controller.AppMetadataController {
	inMemDBClient := client.NewInMemDBClient()
	inMemAppMetadataDao := dao.NewInMemAppMetadataDao(inMemDBClient)
	appMetadataBizLogic := bizlogic.NewAppMetadataBizLogic(inMemAppMetadataDao)
	appMetadataController := controller.NewAppMetadataController(appMetadataBizLogic)
	return appMetadataController
}
